<?php
/**
 * Live Activity API Endpoint
 * Returns recent activity for real-time social proof
 */

// Include database configuration
require_once '../config/database.php';

// Set CORS headers
setCORSHeaders();

try {
    // Get database connection
    $db = getDB();
    
    // Handle different HTTP methods
    switch ($_SERVER['REQUEST_METHOD']) {
        case 'GET':
            handleGetActivity($db);
            break;
        case 'POST':
            handleCreateActivity($db);
            break;
        case 'DELETE':
            handleDeleteActivity($db);
            break;
        default:
            errorResponse('Method not allowed', 405);
    }
    
} catch (Exception $e) {
    errorResponse('Server error: ' . $e->getMessage(), 500);
}

/**
 * Get recent live activity
 */
function handleGetActivity($db) {
    try {
        // Check if table exists first
        $tableCheck = $db->query("SHOW TABLES LIKE 'live_activity'");
        if ($tableCheck->rowCount() === 0) {
            // Table doesn't exist, return empty array
            successResponse([
                'activities' => [],
                'count' => 0,
                'note' => 'Live activity table not found'
            ]);
            return;
        }
        
        // Get filter parameters
        $limit = $_GET['limit'] ?? 20;
        $hours = $_GET['hours'] ?? 24; // Activity from last 24 hours by default
        
        // Build query for recent activity
        $sql = "SELECT * FROM live_activity 
                WHERE active = TRUE 
                AND timestamp >= DATE_SUB(NOW(), INTERVAL :hours HOUR)
                ORDER BY timestamp DESC";
        
        if ($limit && is_numeric($limit)) {
            $sql .= " LIMIT :limit";
        }
        
        $stmt = $db->prepare($sql);
        $stmt->bindValue(':hours', (int)$hours, PDO::PARAM_INT);
        
        if ($limit && is_numeric($limit)) {
            $stmt->bindValue(':limit', (int)$limit, PDO::PARAM_INT);
        }
        
        $stmt->execute();
        $activities = $stmt->fetchAll();
        
        // Format activities for frontend
        $formattedActivities = array_map(function($activity) {
            return [
                'id' => (int)$activity['id'],
                'action' => $activity['action_type'],
                'location' => $activity['location'],
                'amount' => $activity['amount'],
                'product' => $activity['product_name'],
                'client' => $activity['client_name'],
                'time' => $activity['timestamp'],
                'timeAgo' => calculateTimeAgo($activity['timestamp']),
                'autoGenerated' => (bool)$activity['auto_generated']
            ];
        }, $activities);
        
        // Get activity statistics
        $statsQuery = "SELECT 
                        COUNT(*) as total_today,
                        COUNT(CASE WHEN action_type = 'New Order Placed' THEN 1 END) as orders_today,
                        COUNT(CASE WHEN action_type = 'Quote Requested' THEN 1 END) as quotes_today
                       FROM live_activity 
                       WHERE active = TRUE 
                       AND DATE(timestamp) = CURDATE()";
        
        $statsStmt = $db->prepare($statsQuery);
        $statsStmt->execute();
        $stats = $statsStmt->fetch();
        
        successResponse([
            'activities' => $formattedActivities,
            'count' => count($formattedActivities),
            'statistics' => [
                'totalToday' => (int)$stats['total_today'],
                'ordersToday' => (int)$stats['orders_today'],
                'quotesToday' => (int)$stats['quotes_today']
            ],
            'timestamp' => date('Y-m-d H:i:s')
        ]);
        
    } catch (Exception $e) {
        errorResponse('Failed to fetch activity: ' . $e->getMessage());
    }
}

/**
 * Create new activity entry (Admin only)
 */
function handleCreateActivity($db) {
    try {
        // Get JSON data
        $input = json_decode(file_get_contents('php://input'), true);
        
        // Validate required fields
        $required = ['action_type', 'location'];
        foreach ($required as $field) {
            if (!isset($input[$field]) || empty(trim($input[$field]))) {
                errorResponse("Missing required field: $field");
            }
        }
        
        // Insert new activity
        $sql = "INSERT INTO live_activity (action_type, location, amount, product_name, client_name, auto_generated) 
                VALUES (:action_type, :location, :amount, :product_name, :client_name, :auto_generated)";
        
        $stmt = $db->prepare($sql);
        $stmt->execute([
            ':action_type' => trim($input['action_type']),
            ':location' => trim($input['location']),
            ':amount' => trim($input['amount'] ?? ''),
            ':product_name' => trim($input['product_name'] ?? ''),
            ':client_name' => trim($input['client_name'] ?? ''),
            ':auto_generated' => $input['auto_generated'] ?? false
        ]);
        
        $activityId = $db->lastInsertId();
        
        successResponse([
            'id' => $activityId,
            'message' => 'Activity created successfully'
        ]);
        
    } catch (Exception $e) {
        errorResponse('Failed to create activity: ' . $e->getMessage());
    }
}

/**
 * Delete activity (Admin only)
 */
function handleDeleteActivity($db) {
    try {
        $input = json_decode(file_get_contents('php://input'), true);
        
        if (!isset($input['id'])) {
            errorResponse('Activity ID is required');
        }
        
        // Soft delete (set active = false)
        $sql = "UPDATE live_activity SET active = FALSE WHERE id = :id";
        $stmt = $db->prepare($sql);
        $stmt->execute([':id' => $input['id']]);
        
        if ($stmt->rowCount() === 0) {
            errorResponse('Activity not found', 404);
        }
        
        successResponse(['message' => 'Activity deleted successfully']);
        
    } catch (Exception $e) {
        errorResponse('Failed to delete activity: ' . $e->getMessage());
    }
}

/**
 * Auto-generate realistic activity entries
 */
function generateSampleActivity($db) {
    $actionTypes = [
        'New Order Placed',
        'Quote Requested', 
        'Sample Approved',
        'Contract Signed',
        'Shipment Delivered',
        'New Inquiry'
    ];
    
    $locations = [
        'Germany', 'Netherlands', 'USA', 'Italy', 'Spain', 'France',
        'Belgium', 'UK', 'Canada', 'Australia', 'Japan', 'UAE'
    ];
    
    $products = [
        'Premium Arabica AA', 'Arabica AB Grade', 'Superior Robusta Grade 1',
        'Premium Cocoa Beans', 'Organic Arabica'
    ];
    
    $companies = [
        'Munich Coffee Roasters', 'Amsterdam Trading Co.', 'New York Imports',
        'Milano Chocolate Ltd.', 'Barcelona Coffee Co.', 'Paris Specialty Coffee',
        'Brussels Roasters', 'London Coffee House', 'Toronto Imports',
        'Sydney Coffee Co.', 'Tokyo Trading', 'Dubai Coffee LLC'
    ];
    
    // Generate 3-5 new activities
    $count = rand(3, 5);
    
    for ($i = 0; $i < $count; $i++) {
        $action = $actionTypes[array_rand($actionTypes)];
        $location = $locations[array_rand($locations)];
        $product = $products[array_rand($products)];
        $company = $companies[array_rand($companies)];
        $amount = rand(50, 500) . ' MT';
        
        // Random timestamp within last 2 hours
        $minutesAgo = rand(5, 120);
        
        $sql = "INSERT INTO live_activity (action_type, location, amount, product_name, client_name, timestamp, auto_generated) 
                VALUES (:action_type, :location, :amount, :product_name, :client_name, 
                        DATE_SUB(NOW(), INTERVAL :minutes MINUTE), TRUE)";
        
        $stmt = $db->prepare($sql);
        $stmt->execute([
            ':action_type' => $action,
            ':location' => $location,
            ':amount' => $amount,
            ':product_name' => $product,
            ':client_name' => $company,
            ':minutes' => $minutesAgo
        ]);
    }
}

/**
 * Calculate human-readable time ago
 */
function calculateTimeAgo($timestamp) {
    $time = time() - strtotime($timestamp);
    
    if ($time < 60) {
        return 'Just now';
    } elseif ($time < 3600) {
        $minutes = floor($time / 60);
        return $minutes . ' minute' . ($minutes > 1 ? 's' : '') . ' ago';
    } elseif ($time < 86400) {
        $hours = floor($time / 3600);
        return $hours . ' hour' . ($hours > 1 ? 's' : '') . ' ago';
    } else {
        $days = floor($time / 86400);
        return $days . ' day' . ($days > 1 ? 's' : '') . ' ago';
    }
}

// Auto-generate sample activity if requested
if (isset($_GET['generate']) && $_GET['generate'] === 'true') {
    generateSampleActivity($db);
    successResponse(['message' => 'Sample activity generated successfully']);
}
?>